contact_links:
- name: Check out the InvUI Documentation
  about: Please read the documentation before asking a question.
  url: https://docs.xenondevs.xyz/invui1/
- name: Ask a question on GitHub
  about: You can use GitHub Discussions to ask a question.
  url: https://github.com/carlodrift/InvUI/discussions
